apiVersion: multitenancy.istio.eoinfennessy.com/v1alpha1
kind: Zone
metadata:
  labels:
    app.kubernetes.io/name: istio-multitenancy
    app.kubernetes.io/managed-by: kustomize
  name: zone-sample
spec:
  # TODO(user): Add fields here
